# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  launcher:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
        python: [ '3.8', '3.9' ]
    name: "Launcher: py-${{ matrix.python }} on ${{ matrix.os }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Update PYTHONPATH
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:$(pwd)/src" >> "${GITHUB_ENV}"

      - name: Install Python deps for lint checks
        run: |
          python -m pip install --upgrade pylint ruff

      - name: Run Pylint checks
        run: |
          python -m pylint $(git ls-files -- '*.py' ':!:third_party/' ':!:console/')
        continue-on-error: true

      - name: Run Ruff checks
        run: |
          python -m ruff check --exclude=third_party examples/ src/ tests/
        continue-on-error: true

  console:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
        python: [ '3.8', '3.9' ]
    name: "Console: py-${{ matrix.python }} on ${{ matrix.os }}"
    defaults:
      run:
        working-directory: ./console/appengine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install general Python deps
        run: |
          python -m pip install -r requirements.txt

      - name: Install testing Python deps
        run: |
          python -m pip install -r requirements-test.txt

      - name: Install Python deps for lint checks
        run: |
          python -m pip install --upgrade pylint ruff

      - name: Run Pylint checks
        run: |
          python -m pylint $(git ls-files -- '*.py')
        continue-on-error: true

      - name: Run Ruff checks
        run: |
          python -m ruff check .
        continue-on-error: true
